SOURCES = locations2 test_voice2 test_item2 test_char2 item_list
OTHER = test_bgm2 map dir

include mk.common

clean::

test:

install:
	ruby install_drama.rb ../../user/my_uid/1/work/drama/ $(SOURCES)
